theme: jekyll-theme-minimal
url: "https://beijingbitcoinmeetup.github.io/noded" 
title: Beijing Bitcoin Meetup - Noded Edition
logo: "https://beijingbitcoinmeetup.github.io/noded/assets/BC_Logo_128.png"
